### ISSUE TITLE
[DELETE_FAILED_USER_RESTRICTED]

### ISSUE THREAD

**Issue by Korb** [varunsainihr04/vivo_bloatware_remover#2]
## Action
```
echo Deleting  Vivo App Store
adb shell pm uninstall -k --user 0 com.vivo.appstore
```

## Result
`Failure [DELETE_FAILED_USER_RESTRICTED]`

## Environment
Android Debug Bridge version 1.0.41
Version 35.0.2-12147458
Running on Windows 10.0.19045

OS version: Funtouch OS 14
Model: Vivo T1 (4G,  V2153)
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.9.0.W20
Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.107
Kernel version: 4.19.157-perf+, 1 Sat Oct 12 11:14:50 CST 2024
Compile time: 12 Oct 2024 06:06:30
Android security update: 1 October 2024
Google Play system update: 1 September 2024
Software parameter update: 15 October 2024

**Comment by varunsainiau** [comment]
It’s doesn’t work on Vivo App Store, Manager.
